matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4, 4)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 5, 5)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 6, 6)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 7, 7)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 8, 8)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 9, 9)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 10, 10)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 11, 11)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 12, 12)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 13, 13)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 14, 14)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 15, 15)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 16, 16)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 17, 17)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 18, 18)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 19, 19)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 20, 20)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 21, 21)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 22, 22)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 23, 23)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 24, 24)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 25, 25)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 26, 26)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 27, 27)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 28, 28)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 29, 29)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 30, 30)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 31, 31)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 32, 32)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 33, 33)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 34, 34)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 35, 35)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 36, 36)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 37, 37)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 38, 38)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 39, 39)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 40, 40)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 41, 41)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 42, 42)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 43, 43)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 44, 44)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 45, 45)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 46, 46)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 47, 47)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 48, 48)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 49, 49)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 50, 50)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 51, 51)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 52, 52)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 53, 53)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 54, 54)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 55, 55)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 56, 56)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 57, 57)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 58, 58)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 59, 59)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 60, 60)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 61, 61)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 62, 62)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 63, 63)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 64, 64)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 65, 65)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 66, 66)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 67, 67)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 68, 68)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 69, 69)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 70, 70)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 71, 71)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 72, 72)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 73, 73)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 74, 74)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 75, 75)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 76, 76)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 77, 77)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 78, 78)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 79, 79)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 80, 80)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 81, 81)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 82, 82)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 83, 83)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 84, 84)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 85, 85)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 86, 86)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 87, 87)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 88, 88)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 89, 89)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 90, 90)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 91, 91)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 92, 92)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 93, 93)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 94, 94)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 95, 95)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 96, 96)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 97, 97)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 98, 98)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 99, 99)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 100, 100)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 101, 101)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 102, 102)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 103, 103)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 104, 104)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 105, 105)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 106, 106)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 107, 107)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 108, 108)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 109, 109)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 110, 110)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 111, 111)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 112, 112)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 113, 113)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 114, 114)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 115, 115)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 116, 116)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 117, 117)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 118, 118)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 119, 119)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 120, 120)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 121, 121)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 122, 122)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 123, 123)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 124, 124)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 125, 125)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 126, 126)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 127, 127)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 128, 128)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 129, 129)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 130, 130)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 131, 131)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 132, 132)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 133, 133)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 134, 134)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 135, 135)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 136, 136)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 137, 137)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 138, 138)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 139, 139)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 140, 140)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 141, 141)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 142, 142)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 143, 143)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 144, 144)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 145, 145)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 146, 146)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 147, 147)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 148, 148)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 149, 149)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 150, 150)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 151, 151)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 152, 152)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 153, 153)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 154, 154)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 155, 155)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 156, 156)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 157, 157)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 158, 158)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 159, 159)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 160, 160)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 161, 161)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 162, 162)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 163, 163)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 164, 164)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 165, 165)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 166, 166)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 167, 167)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 168, 168)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 169, 169)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 170, 170)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 171, 171)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 172, 172)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 173, 173)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 174, 174)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 175, 175)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 176, 176)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 177, 177)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 178, 178)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 179, 179)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 180, 180)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 181, 181)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 182, 182)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 183, 183)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 184, 184)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 185, 185)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 186, 186)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 187, 187)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 188, 188)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 189, 189)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 190, 190)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 191, 191)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 192, 192)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 193, 193)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 194, 194)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 195, 195)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 196, 196)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 197, 197)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 198, 198)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 199, 199)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 200, 200)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 201, 210)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 211, 220)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 221, 230)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 231, 240)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 241, 250)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 251, 260)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 261, 270)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 271, 280)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 281, 290)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 291, 300)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 301, 310)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 311, 320)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 321, 330)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 331, 340)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 341, 350)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 351, 360)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 361, 370)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 371, 380)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 381, 390)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 391, 400)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 401, 410)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 411, 420)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 421, 430)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 431, 440)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 441, 450)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 451, 460)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 461, 470)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 471, 480)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 481, 490)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 491, 500)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 501, 510)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 511, 520)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 521, 530)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 531, 540)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 541, 550)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 551, 560)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 561, 570)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 571, 580)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 581, 590)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 591, 600)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 601, 610)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 611, 620)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 621, 630)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 631, 640)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 641, 650)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 651, 660)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 661, 670)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 671, 680)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 681, 690)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 691, 700)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 701, 710)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 711, 720)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 721, 730)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 731, 740)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 741, 750)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 751, 760)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 761, 770)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 771, 780)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 781, 790)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 791, 800)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 801, 810)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 811, 820)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 821, 830)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 831, 840)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 841, 850)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 851, 860)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 861, 870)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 871, 880)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 881, 890)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 891, 900)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 901, 910)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 911, 920)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 921, 930)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 931, 940)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 941, 950)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 951, 960)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 961, 970)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 971, 980)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 981, 990)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 991, 1000)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1001, 1010)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1011, 1020)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1021, 1030)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1031, 1040)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1041, 1050)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1051, 1060)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1061, 1070)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1071, 1080)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1081, 1090)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1091, 1100)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1101, 1110)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1111, 1120)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1121, 1130)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1131, 1140)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1141, 1150)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1151, 1160)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1161, 1170)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1171, 1180)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1181, 1190)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1191, 1200)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1201, 1210)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1211, 1220)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1221, 1230)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1231, 1240)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1241, 1250)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1251, 1260)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1261, 1270)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1271, 1280)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1281, 1290)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1291, 1300)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1301, 1310)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1311, 1320)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1321, 1330)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1331, 1340)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1341, 1350)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1351, 1360)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1361, 1370)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1371, 1380)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1381, 1390)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1391, 1400)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1401, 1410)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1411, 1420)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1421, 1430)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1431, 1440)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1441, 1450)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1451, 1460)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1461, 1470)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1471, 1480)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1481, 1490)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1491, 1500)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1501, 1510)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1511, 1520)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1521, 1530)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1531, 1540)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1541, 1550)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1551, 1560)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1561, 1570)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1571, 1580)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1581, 1590)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1591, 1600)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1601, 1610)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1611, 1620)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1621, 1630)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1631, 1640)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1641, 1650)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1651, 1660)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1661, 1670)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1671, 1680)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1681, 1690)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1691, 1700)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1701, 1710)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1711, 1720)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1721, 1730)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1731, 1740)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1741, 1750)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1751, 1760)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1761, 1770)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1771, 1780)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1781, 1790)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1791, 1800)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1801, 1810)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1811, 1820)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1821, 1830)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1831, 1840)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1841, 1850)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1851, 1860)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1861, 1870)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1871, 1880)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1881, 1890)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1891, 1900)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1901, 1910)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1911, 1920)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1921, 1930)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1931, 1940)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1941, 1950)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1951, 1960)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1961, 1970)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1971, 1980)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1981, 1990)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 1991, 2000)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2001, 2010)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2011, 2020)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2021, 2030)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2031, 2040)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2041, 2050)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2051, 2060)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2061, 2070)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2071, 2080)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2081, 2090)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2091, 2100)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2101, 2110)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2111, 2120)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2121, 2130)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2131, 2140)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2141, 2150)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2151, 2160)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2161, 2170)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2171, 2180)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2181, 2190)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2191, 2200)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2201, 2210)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2211, 2220)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2221, 2230)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2231, 2240)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2241, 2250)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2251, 2260)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2261, 2270)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2271, 2280)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2281, 2290)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2291, 2300)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2301, 2310)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2311, 2320)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2321, 2330)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2331, 2340)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2341, 2350)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2351, 2360)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2361, 2370)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2371, 2380)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2381, 2390)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2391, 2400)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2401, 2410)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2411, 2420)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2421, 2430)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2431, 2440)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2441, 2450)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2451, 2460)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2461, 2470)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2471, 2480)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2481, 2490)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2491, 2500)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2501, 2510)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2511, 2520)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2521, 2530)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2531, 2540)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2541, 2550)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2551, 2560)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2561, 2570)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2571, 2580)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2581, 2590)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2591, 2600)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2601, 2610)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2611, 2620)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2621, 2630)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2631, 2640)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2641, 2650)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2651, 2660)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2661, 2670)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2671, 2680)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2681, 2690)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2691, 2700)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2701, 2710)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2711, 2720)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2721, 2730)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2731, 2740)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2741, 2750)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2751, 2760)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2761, 2770)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2771, 2780)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2781, 2790)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2791, 2800)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2801, 2810)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2811, 2820)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2821, 2830)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2831, 2840)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2841, 2850)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2851, 2860)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2861, 2870)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2871, 2880)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2881, 2890)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2891, 2900)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2901, 2910)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2911, 2920)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2921, 2930)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2931, 2940)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2941, 2950)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2951, 2960)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2961, 2970)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2971, 2980)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2981, 2990)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 2991, 3000)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3001, 3010)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3011, 3020)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3021, 3030)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3031, 3040)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3041, 3050)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3051, 3060)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3061, 3070)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3071, 3080)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3081, 3090)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3091, 3100)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3101, 3110)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3111, 3120)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3121, 3130)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3131, 3140)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3141, 3150)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3151, 3160)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3161, 3170)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3171, 3180)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3181, 3190)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3191, 3200)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3201, 3210)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3211, 3220)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3221, 3230)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3231, 3240)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3241, 3250)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3251, 3260)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3261, 3270)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3271, 3280)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3281, 3290)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3291, 3300)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3301, 3310)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3311, 3320)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3321, 3330)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3331, 3340)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3341, 3350)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3351, 3360)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3361, 3370)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3371, 3380)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3381, 3390)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3391, 3400)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3401, 3410)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3411, 3420)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3421, 3430)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3431, 3440)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3441, 3450)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3451, 3460)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3461, 3470)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3471, 3480)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3481, 3490)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3491, 3500)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3501, 3510)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3511, 3520)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3521, 3530)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3531, 3540)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3541, 3550)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3551, 3560)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3561, 3570)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3571, 3580)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3581, 3590)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3591, 3600)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3601, 3610)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3611, 3620)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3621, 3630)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3631, 3640)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3641, 3650)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3651, 3660)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3661, 3670)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3671, 3680)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3681, 3690)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3691, 3700)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3701, 3710)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3711, 3720)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3721, 3730)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3731, 3740)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3741, 3750)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3751, 3760)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3761, 3770)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3771, 3780)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3781, 3790)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3791, 3800)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3801, 3810)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3811, 3820)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3821, 3830)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3831, 3840)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3841, 3850)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3851, 3860)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3861, 3870)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3871, 3880)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3881, 3890)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3891, 3900)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3901, 3910)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3911, 3920)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3921, 3930)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3931, 3940)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3941, 3950)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3951, 3960)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3961, 3970)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3971, 3980)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3981, 3990)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 3991, 4000)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4001, 4010)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4011, 4020)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4021, 4030)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4031, 4040)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4041, 4050)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4051, 4060)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4061, 4070)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4071, 4080)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4081, 4090)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4091, 4100)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4101, 4110)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4111, 4120)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4121, 4130)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4131, 4140)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4141, 4150)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4151, 4160)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4161, 4170)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4171, 4180)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4181, 4190)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4191, 4200)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4201, 4210)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4211, 4220)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4221, 4230)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4231, 4240)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4241, 4250)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4251, 4260)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4261, 4270)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4271, 4280)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4281, 4290)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4291, 4300)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4301, 4310)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4311, 4320)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4321, 4330)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4331, 4340)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4341, 4350)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4351, 4360)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4361, 4370)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4371, 4380)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4381, 4390)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4391, 4400)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4401, 4410)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4411, 4420)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4421, 4430)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4431, 4440)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4441, 4450)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4451, 4460)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4461, 4470)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4471, 4480)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4481, 4490)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4491, 4500)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4501, 4510)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4511, 4520)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4521, 4530)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4531, 4540)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4541, 4550)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4551, 4560)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4561, 4570)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4571, 4580)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4581, 4590)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4591, 4600)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4601, 4610)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4611, 4620)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4621, 4630)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4631, 4640)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4641, 4650)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4651, 4660)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4661, 4670)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4671, 4680)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4681, 4690)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4691, 4700)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4701, 4710)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4711, 4720)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4721, 4730)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4731, 4740)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4741, 4750)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4751, 4760)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4761, 4770)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4771, 4780)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4781, 4790)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4791, 4800)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4801, 4810)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4811, 4820)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4821, 4830)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4831, 4840)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4841, 4850)" &
wait
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4851, 4860)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4861, 4870)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4871, 4880)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4881, 4890)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4891, 4900)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4901, 4910)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4911, 4920)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4921, 4930)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4931, 4940)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4941, 4950)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4951, 4960)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4961, 4970)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4971, 4980)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4981, 4990)" &
matlab -nodisplay -r "densetraj_encode_sge('video-bg', 4991, 4992)" &
wait
